version: '3.8'

services:
  cache: 
    container_name: cache
    image: redis
    ports:
      - "6399:6399"

  db: 
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data

  api:
    container_name: api
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    

    depends_on:
      - db
      - cache

