"""transaction2

Revision ID: b7ea8c2447bc
Revises: f4ba418fe1e6
Create Date: 2022-05-18 21:38:18.194428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ea8c2447bc'
down_revision = 'f4ba418fe1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column(
        'updated_at', sa.String(), nullable=True))
    op.drop_column('transactions', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column(
        'updateed_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'updated_at')
    # ### end Alembic commands ###
