"""transaction migration

Revision ID: f4ba418fe1e6
Revises: 
Create Date: 2022-05-14 23:55:45.130012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ba418fe1e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.create_table('transactions',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('trans_id', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('from_user', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('to_user', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('amount', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('currency_type', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('transaction_type', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('updateed_at', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='transactions_pkey'),
                    sa.UniqueConstraint(
                        'trans_id', name='transactions_trans_id_key')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('trans_id', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('from_user', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('to_user', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('currency_type', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('transaction_type', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('updateed_at', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='transactions_pkey'),
                    sa.UniqueConstraint(
                        'trans_id', name='transactions_trans_id_key')
                    )
    # ### end Alembic commands ###
